dist: xenial

sudo: true

before_install:
  - sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver pool.sks-keyservers.net 2649A5A9 || { sudo wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -; }
  - sudo apt-get update
  - sudo apt-get install -y singularity-container
  - wget https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64
  - mv gdrive-linux-x64 gdrive
  - chmod +x gdrive
  - mkdir gdrive-config
  - echo $GOOGLE_KEY > gdrive-config/token_v2.json

jobs:
  include:
    - stage: build
      script: travis_wait 60 sudo singularity build singularity_tractoflow.img singularity_tractoflow.def
    - stage: test
      script: singularity exec singularity_tractoflow.img echo "Singularity test"
    - stage: deploy
      script:
        - travis_wait 30 ./gdrive upload -c gdrive-config singularity_tractoflow.img -p $GOOGLE_DIR --name singularity_tractoflow.img
        - echo $TRAVIS_COMMIT > README
        - ./gdrive upload -c gdrive-config README -p $GOOGLE_DIR --name README_singularity_tractoflow
