dist: xenial

before_install:
  - sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver pool.sks-keyservers.net 2649A5A9 || { sudo wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -; }
  - sudo apt-get update
  - sudo apt-get install -y singularity-container

jobs:
  include:
    - stage: build Docker image
      script:
        - travis_wait 60 docker build -t docker_tractoflow .
        - docker images
        - 'if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi'
        - 'if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then docker tag docker_tractoflow $DOCKER_USERNAME/docker-tractoflow:latest; fi'
        - 'if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then travis_wait 60 docker push $DOCKER_USERNAME/docker-tractoflow:latest; fi'
